### ISSUE TITLE
Relationships on deleted classes need to cascade delete

### ISSUE THREAD

**Issue by jkcarney** [mucsci-students/2021fa-420-JSMACH#33]
- Add two classes, Class1, Class2
- Add relationship between Class1 and Class2
- Delete Class1
- SHOULD also delete relationship, since a relationship is only valid between two existing classes
- Add some kind of cascade_delete() method

**Comment by helittl1** [comment]
Method written to cascade delete relationships where deleted class is either a source or destination.
'ensure_relationship_delete' in UMLModel
